### ISSUE TITLE
error when call a php function with uppercase

### ISSUE THREAD

**Issue by Lidsacae** [iqbalfn/exec-php#10]
Hi,
It's possible to call a php function with uppercase ? like `myFunctionLikeThis()` .
I've an error on node when i use uppercase.

Thanks

**Comment by iqbalfn** [comment]
Well, it's already on readme file:

    All uppercase function name on PHP will be converted to lowercase on exec-php.

And I don't found solution for this for now as PHP show all function as lowercase, and PHP ignore case on function anyway.
