### ISSUE TITLE
When calling a php script a second time, it doesn't execute the code again

### ISSUE THREAD

**Issue by LisaMaagdenberg** [iqbalfn/exec-php#11]
I am working on an app that responds to certain status changes. Whenever an order changes its status to 2, I run a php file with 
```
execPhp("../php/tasks/task2.php", function(error, php, outprint) {
  console.log(outprint)
  if (error) {
    console.log(error)
   }
})
```

The first time this executes just like I want to, but if another order changes to status 2, the output of the first time running is repeated without the php script being executed again.

I tested this with the following code in task2.php
```
$randnr = rand(0, 1000);
mkdir($config['tmp'].$randnr, 0777, true);
```
And only one dir is made after changing multiple orders to status 2.

Is this normal or am I missing something?

**Comment by iqbalfn** [comment]
How do I just get this issue 2 days after issued.

Well, it's actually normal as calling `execPhp` will cache the result, but won't cache function call. The best way to solve this issue is by creating function inside your php file, and call it from nodejs. And it's the recommended way to do that.

```php
<?php
// task.php

function make_dir(){
    $rand = rand(0, 1000);
    mkdir($config['tmp'] . $rand, 0777, true);
}
```

```js
// index.js
var execPhp = require('exec-php');

execPhp('task2.php', function(e, php, op){
    php.make_dir(function(e,r,o,p){
        if(e){
            console.log(e);
        }
    });
});
```
I try your script, and I can confirm it's not execute next call. But by doing above way, it just work as expected. I'll just close this issue, and please reopen if it's not solve your case.

**Comment by LisaMaagdenberg** [comment]
Thanks for the response and explanation. I got it to work today!

**Comment by ayophanz** [comment]
Hi, I have the same issue but when I try your solution it gives me " is not a function".

**Comment by iqbalfn** [comment]
It's easier to check if you can provide a simple script that you use.

**Comment by ayophanz** [comment]
Sending.php
`function runSms() {
    echo "test";
}`

app.js
`execPhp('Sending.php', function(error, php, outprint){
       php.runSms(function(e,r,o,p){
            //something here...
       });
 });`

error
![image](https://user-images.githubusercontent.com/24581584/62511507-acedd500-b846-11e9-9e60-0bd4a528d007.png)

**Comment by iqbalfn** [comment]
Have you try call the function with all lowercase? It's on README file of this project.

**Comment by ayophanz** [comment]
Ok thanks I'll try
