### ISSUE TITLE
app crash due to not closing file

### ISSUE THREAD

**Issue by MHDMAM** [iqbalfn/exec-php#19]
I was getting app crash coz of the high number of fd that linked to my app pid.
after going through the code I can see you only unlink the file  **which doesn't close the file, only removed it**
at:
https://github.com/iqbalfn/exec-php/blob/711fa5b8657cdf17a289303cf5440ba136a447a8/lib/cli.js#L57
and here:
https://github.com/iqbalfn/exec-php/blob/711fa5b8657cdf17a289303cf5440ba136a447a8/lib/cli.js#L58

we need to add the following at L56:
``` JS
fs.close(fd,closeCB);
fs.close(fds,closeCB);
```

**Comment by iqbalfn** [comment]
You could help by fixing the bug, test it, and make some pull request. I'll really happy to accept the request.

**Comment by MHDMAM** [comment]
here's a PR, please check and accept. https://github.com/iqbalfn/exec-php/pull/20

**Comment by iqbalfn** [comment]
Just deploy to npm as well. Please reopen if the error appear.
