### ISSUE TITLE
How to use exec-php in MVC framework like zend?

### ISSUE THREAD

**Issue by Parthvora** [iqbalfn/exec-php#2]
Basically what I want to do over here is to get data into node server js, data which is returned from a function which is written into a Zend model.

My node js server code is as below:

    var socket = require( 'socket.io' );
    var express = require( 'express' );
    var http = require( 'http' );
    var execPhp = require('exec-php');
 
    var app = express();
    var server = http.createServer( app );

    var io = socket.listen( server );

    execPhp('../application/modules/front/models/Dbtable/Postcontent.php', 
    function(error, php, outprint){
    php.fetchEntryAll(function(error, result){
    io.sockets.emit('showfeeds', result);
    });
    });

    server.listen( 7000 );

so when I tried to execute above code it gives me error like below:

Error: Command failed: PHP Fatal error: Class 'Zend_Db_Table_Abstract' not found in /Data/www/XXX/application/modules/front/models/Dbtable/Postcontent.php on line 3

same code works when I use core PHP instead of Zend.

So I believe that we can't use OOP stuff with exec-php.

Is there any solution here?

**Comment by iqbalfn** [comment]
I believe all PHP Framework has init script that do various stuff before calling some model. While executing php file from exec-php will skip all that initialization. I've no idea how to do that. You could create single PHP file that call zend init script and that model, and call the new file by exec-php.
