### ISSUE TITLE
Error in some files

### ISSUE THREAD

**Issue by SamboVisal** [iqbalfn/exec-php#21]
`SyntaxError: Unexpected end of JSON input`

I am using version 0.0.5

And this is error
![screen shot 2562-01-30 at 3 44 06 pm](https://user-images.githubusercontent.com/29918870/51969074-12cb5f80-24a6-11e9-9f24-d1be98b0e74a.png)

This is code in Node jS

    execPhp('test.php', function(error, php, outprint){
  
    });

Test.php

    <?php
    echo "One";

**Comment by iqbalfn** [comment]
I can't reproduce this. Could you point me to the way to reproduce the error? Other environment informations may help to identify the error.

**Comment by Stiveknx** [comment]
I've got this error, when on my php file I've had an function commented:

```
/*
function foo(){
echo 'bar';
}
*/
```

**Comment by iqbalfn** [comment]
Are you telling me the error happened when the called function is not exists on PHP file?
