### ISSUE TITLE
Cannot read property 'my_function' of undefined

### ISSUE THREAD

**Issue by SamboVisal** [iqbalfn/exec-php#22]
I was trying to execute php file but got some errors
     
    <?php

    echo 'This is php file';

     function my_function($voipToken){
    
         $deviceToken = $voipToken;

         echo $deviceToken;`

 This is I called it from Node js script
         execPhp('php/app.php', function(error, php, outprint){
                   
           console.log(error)
           php.my_function(deviceToken, function(err, result, output, printed){
           if (result) {
             console.log("This is message " + printed)
             console.log("This is result " + result) 
           } else {
               console.log("false sending " + result)
            }

**Comment by iqbalfn** [comment]
What's the output of your code `console.log(error)`?

**Comment by SamboVisal** [comment]
This is the error message
![error](https://user-images.githubusercontent.com/29918870/55449508-02df1180-55f6-11e9-8eac-242eb2e5de5a.PNG)

**Comment by SamboVisal** [comment]
@iqbalfn sometime it works fine, but sometime it doesn't work properly.

**Comment by SamboVisal** [comment]
@iqbalfn Can u check the whole PHP code because sometime I got error : SyntaxError: Unexpected end of JSON input

`<?php
// Put your device token here (without spaces):
function my_function($voipToken){

    $deviceToken = $voipToken;
    // Put your private key's passphrase here:
    $passphrase = '1234';
    // Put your alert message here:
    $message = 'My first push notification!';

    $ctx = stream_context_create();
    stream_context_set_option($ctx, 'ssl', 'local_cert', 'voip.pem');
    stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);
    // Open a connection to the APNS server
    $fp = stream_socket_client(
    //  'ssl://gateway.push.apple.com:2195', $err,
    'ssl://gateway.sandbox.push.apple.com:2195', $err,
    $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

    if (!$fp)
    exit("Failed to connect: $err $errstr" . PHP_EOL);
    // Create the payload body
    $body['aps'] = array(
                     'content-available'=> 1,
                     'alert' => $message,
                     'sound' => 'default',
                     'badge' => 0,
                     );
    echo $message;
    // Encode the payload as JSON
    $payload = json_encode($body);
    // Build the binary notification
    $msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;
    // Send it to the server
    $result = fwrite($fp, $msg, strlen($msg));
    if (!$result)
        //echo 'Message not delivered' . PHP_EOL; 
        return 'Message not delivered' . PHP_EOL;
    else
        echo 'Message successfully delivered' . PHP_EOL;
        return 'Message successfully delivered' . PHP_EOL;
    fclose($fp);       
}

`

**Comment by SamboVisal** [comment]
Here is another Error that I got
![anothererror](https://user-images.githubusercontent.com/29918870/55450009-08d5f200-55f8-11e9-8d69-d1aa14d9504b.PNG)

Please help me to figure it out

**Comment by iqbalfn** [comment]
If you're using linux? Please show the result of `which php` on your console. I'm afraid the php binary is not yet on your PATH.

**Comment by SamboVisal** [comment]
My bad! Now it is working. Thank you
