### ISSUE TITLE
module.parent is deprecated  

### ISSUE THREAD

**Issue by jakubzasanski** [iqbalfn/exec-php#23]
https://github.com/iqbalfn/exec-php/blob/master/index.js#L34

module.parent is deprecated 
https://nodejs.org/docs/latest/api/deprecations.html#deprecations_dep0144_module_parent

**Comment by iqbalfn** [comment]
Thank you for the info. Do you have some time to fix the issue?  If you can fix the issue, just send me the pull request. Otherwise, I'll see the issue when I've time for that.

**Comment by iqbalfn** [comment]
Version 0.0.6 is already released that remove the `module.parent` syntax.
