### ISSUE TITLE
Working with PHP Classes

### ISSUE THREAD

**Issue by crushton-qg** [iqbalfn/exec-php#24]
Hi,

I am trying to call a function in PHP file which instantiates a class which contains a set of functions and returns said class. However, when I call the getClass function, the result from the JavaScript code is an empty object.

Can this library handle PHP classes?

```php
class upgrade_v5
{
    function __referringUrl($input)
    {
        $value = array_key_exists('campaign_id', $input) && isset($input['campaign_id']) && $input['campaign_id'] !== false && $input['campaign_id'] !== '' ? $input['campaign_id'] : '';

        return $value;
    }
}

function getPoster()
{
    $poster = new upgrade_v5();

    return $poster;
}
```

```js
execPhp('execPhpTest.php', function(error, php, outprint){
        php.getposter(function(error, result){
            console.error(error);
            console.log(result);
        });
    });
```

**Console output:**

```
false {}
```

**Comment by iqbalfn** [comment]
No, that's not possible as PHP class is not compatible to JS class. The only thing that can be returned is anything that can be encoded to string.
