### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by ufukOzarslan** [iqbalfn/exec-php#25]
Hi,

1|report  | SyntaxError: Unexpected token u in JSON at position 0
1|report  |     at JSON.parse (<anonymous>)
1|report  |     at exec (/PUBLIC/socket/node_modules/exec-php/index.js:71:26)
1|report  |     at ChildProcess.exithandler (child_process.js:285:7)
1|report  |     at ChildProcess.emit (events.js:198:13)
1|report  |     at maybeClose (internal/child_process.js:982:16)
1|report  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

where is the problem? The data I sent is the same as yours.

**Comment by iqbalfn** [comment]
Please be more specific. Show me your code.

**Comment by nowaysgit** [comment]
+
```
[1] undefined:1 
[1] undefined
[1] ^
[1]
[1] SyntaxError: Unexpected token u in JSON at position 0
[1]     at JSON.parse (<anonymous>)
[1]     at C:\Users\noways\Desktop\WORK\parsing_meeting\scraber\node_modules\exec-php\index.js:71:26
[1]     at ChildProcess.exithandler (node:child_process:388:7)
[1]     at ChildProcess.emit (node:events:390:28)
[1]     at maybeClose (node:internal/child_process:1064:16)
[1]     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

I use Example

PHP:
```
<?php

echo "One";
function my_function($arg1, $arg2){
    echo "Two";
    return $arg1 + $arg2;
}

```
JS:
```
let execPhp = require('exec-php');

    execPhp('LoadPhoto.php', (err, php, out) => {
        // outprint is now `One'.

        php.my_function(1, 2, (err, result, output, printed) => {
            // result is now `3'
            // output is now `One'.
            // printed is now `Two'.
        })
    })
```

**Comment by iqbalfn** [comment]
I really can't reproduce your error. This is the step that I do to retry your error:

```bash
$ mkdir node
$ cd node
$ npm init
  > node
  > 1.0.0
  > 
  > index.js
  > 
  > 
  > 
  > 
  > MIT
  > yes
$ npm i exec-php
```

Next i create the php file named `LoadPhoto.php` in the `node/` directory and fill it with content as below:

```php
<?php

echo "One";
function my_function($arg1, $arg2){
    echo "Two";
    return $arg1 + $arg2;
}
```

Next I create the js file named `index.js` in the `node/` directory and fill it with the content as below:

```js
let execPhp = require('exec-php');

execPhp('LoadPhoto.php', (err, php, out) => {
    php.my_function(1, 2, (err, result, output, printed) => {
        console.log([
            err,
            result,
            output,
            printed
        ])
    })
})
```

Next i run the script with:

```bash
$ node index.js
```

And the output:

```bash
[ false, 3, 'One', 'Two' ]
```
