### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by borisovdmitry** [iqbalfn/exec-php#3]
HI. I do everything as instructed and get the following error (in the screenshot).
Please help me.
![default](https://cloud.githubusercontent.com/assets/7840293/8917378/51f71134-34ba-11e5-86a9-414884a23b7c.png)

**Comment by iqbalfn** [comment]
Could you provide the source code you use exec-php? It's harder to find the problem by error message only.

**Comment by mkanwar** [comment]
I got the same error. I'm just follow your example.
gmPHP.js
![capture](https://cloud.githubusercontent.com/assets/20163563/16373625/bb8f8846-3c85-11e6-9094-4c2e52ea7eb0.PNG)
file.php
![capture2](https://cloud.githubusercontent.com/assets/20163563/16376783/c69ca0e8-3c94-11e6-9a55-0fdc8896b711.PNG)
![run](https://cloud.githubusercontent.com/assets/20163563/16376891/6e7b5764-3c95-11e6-8414-08cf9db237a5.PNG)

Guide me please..

**Comment by iqbalfn** [comment]
As of your source code preview, I see that you're pointing the PHP binary to 'C:/xampp/apache/bin' while execPHP expect it to be path to php.exe ( not quite sure it's called php.exe or php-cgi.exe on xampp ). Please make sure the PHP binary point to correct php.exe/php-cgi.exe on your xampp installation.

I'll reopen the issue, please tell me if it work or not.

**Comment by mkanwar** [comment]
I'm install my xampp in the D:/. The specific location for php.exe is D:\xampp\php\php.exe. It still get the same error when I change the second parameter to "D:/xampp/php"

**Comment by mkanwar** [comment]
Okeh!! I got the solution.. I should specify the parameter to "D:/xampp/php/php.exe
![capture](https://cloud.githubusercontent.com/assets/20163563/16377510/03ebff4e-3c99-11e6-9030-a30ff783ab24.PNG)
"
Thanks!!
