### ISSUE TITLE
How I can return a file?

### ISSUE THREAD

**Issue by jhonnynho** [iqbalfn/exec-php#9]
I im using this library and works perfect, but I want to create a PDF file, and the easy way to me its use a MPDF library.

How I can return a file?

I have this

```
execPhp('script.php', function(error, php, outprint){

        php.my_function( function(err, result, output, printed){
            res.json(result);
        });
    });
```

When I return the file appears this error

undefined:1

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at C:\abria-backend\node_modules\exec-php\lib\cli.js:51:33
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

My sample php script 

```
<?php
include("mpdf/mpdf.php");
function my_function(){
	$mpdf = new mPDF();

// Write some HTML code:

$mpdf->WriteHTML('Hello World');

// Output a PDF file directly to the browser
$mpdf->Output();
    }
?>
```

Thanks

**Comment by iqbalfn** [comment]
The `exec-php` translate anything that PHP print/return as string. While the one that you return is binary, I'm not sure it can be translated to string. The best way to do such thing is to save the PDF to some file, and return path to the file to `exec-php`, then process the file in node.

Take a look at [how to write output to file in mpdf](https://mpdf.github.io/reference/mpdf-functions/output.html)

**Comment by jhonnynho** [comment]
Oh thanks, I found a better way to output a PDF File. The output method of the Mpdf class contains a condition to save a file in a folder and I only return the filename to download!

Thanks for help!
